server:
  port: 5000
  host: 0.0.0.0
  debug: true
  static_folder: ./react/dist
  upload_location: ./uploads

database:
  host: 127.0.0.1
  port: 3500
  user: root
  password: my_SQL_password
  name: ece1779_memcache
  table_names:
    key_image: key_image
    config: config
    status: status

cache:
  host: 127.0.0.1
  port: 5001