server:
  port: 5000
  host: 0.0.0.0
  debug: true
  static_folder: ./react/dist
  upload_location: ./uploads
  cache_url: http://127.0.0.1:5001

database:
  host: 127.0.0.1
  port: 3500
  user: root
  password: my_SQL_password
  name: ece1779_memcache