server:
  port: 5000
  host: 0.0.0.0
  debug: true
  static_folder: ./react/dist
  upload_location: ./uploads

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ece1779pass
  name: ece1779_memcache
  table_names:
    key_image: key_image
    config: config
    status: status

cache:
  host: 127.0.0.1
  port: 5001
  
aws:
  private_key_file: ./ece1779_assignment1_keypair.secret.pem
  credential_file: ./credentials.secret
  ami_id: ami-080ff70d8f5b80ba5
  subnet_id: subnet-005acfeb3976436cd
  security_group_id: sg-0b51a4f8399515236
  ssh_key_name: ece1779_assignment1_keypair

github:
  access_token: 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