server:
  port: 5000
  host: 0.0.0.0
  debug: true
  static_folder: ./react/user/dist
  bucket:
    name: "ece1779assignment2group15"

database:
  # host: ece1779assignment2group15.co0mwaevj3y4.us-east-1.rds.amazonaws.com
  host: 127.0.0.1
  port: 3306
  user: root
  password: ece1779pass
  name: ece1779_memcache
  table_names:
    key_image: key_image

cache:
  host: 127.0.0.1
  port: 5001
  partitions: 16

manager:
  host: 127.0.0.1
  port: 5004
  static_folder: ./react/manager/dist
  
auto_scaler:
  port: 5010

aws:
  # for ssh access
  private_key_file: C:/Users/13698/.ssh/ece1779_assignment1_keypair.pem
  # for boto3 access
  credential_file: C:/Users/13698/.aws/credentials
  # for ec2 instance creatation
  ami_id: ami-080ff70d8f5b80ba5
  subnet_id: subnet-005acfeb3976436cd
  security_group_id: sg-0b51a4f8399515236
  ssh_key_name: ece1779_assignment1_keypair

github:
  access_token: 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